require 'distrib/ruby/tasks'

GEMSPEC = Bundler.load_gemspec(Dir['*.gemspec'].first)

RbSys::ExtensionTask.new(GEMSPEC.name, GEMSPEC) do |ext|
  ext.lib_dir = ['lib', GEMSPEC.name].join('/')
end

task default: %w[build]
