# See: https://github.com/artob/readmer#template-variables
---
label: ASIMOV
title: ASIMOV Software Development Kit (SDK)
summary: |
  [ASIMOV] is a polyglot development platform for [trustworthy neurosymbolic machine intelligence].
