/* automatically generated by rust-bindgen 0.69.4 */

#[doc = " A handle encapsulating SDK state."]
pub type AsiInstance = u64;
#[doc = " An SDK version number as a packed integer."]
pub type AsiVersion = u64;
#[repr(u32)]
#[non_exhaustive]
#[doc = " The set of possible port states."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq, FromPrimitive, ToPrimitive)]
pub enum AsiPortState {
    ASI_PORT_STATE_OPEN = 1,
    ASI_PORT_STATE_CONNECTED = 2,
    ASI_PORT_STATE_CLOSED = 3,
}
#[repr(u32)]
#[non_exhaustive]
#[doc = " The set of possible port types."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq, FromPrimitive, ToPrimitive)]
pub enum AsiPortType {
    ASI_PORT_TYPE_INPUT = 1,
    ASI_PORT_TYPE_OUTPUT = 2,
}
#[repr(i32)]
#[non_exhaustive]
#[doc = " Result codes returned by SDK functions."]
#[must_use]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq, FromPrimitive, ToPrimitive)]
pub enum AsiResult {
    ASI_SUCCESS = 0,
    ASI_TIMEOUT_EXPIRED = 1,
    ASI_ERROR_NOT_IMPLEMENTED = -1,
    ASI_ERROR_PRECONDITION_VIOLATED = -2,
    ASI_ERROR_HOST_MEMORY_EXHAUSTED = -3,
    ASI_ERROR_DEVICE_MEMORY_EXHAUSTED = -4,
    ASI_ERROR_SIZE_INSUFFICIENT = -5,
}
#[doc = " A block definition."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiBlockDefinition {
    pub name: [::core::ffi::c_char; 64usize],
    pub input_port_count: u32,
    pub output_port_count: u32,
    pub parameter_count: u32,
}
#[doc = " A block parameter."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiBlockParameter {
    pub name: [::core::ffi::c_char; 64usize],
    pub default_value: [::core::ffi::c_char; 64usize],
}
#[doc = " A block port."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiBlockPort {
    pub name: [::core::ffi::c_char; 64usize],
    pub type_: AsiPortType,
}
#[doc = " A block usage (in a system or flow)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiBlockUsage {
    pub name: [::core::ffi::c_char; 64usize],
    pub type_: [::core::ffi::c_char; 64usize],
}
#[doc = " A flow connection."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiFlowConnection {
    pub source_block: [::core::ffi::c_char; 64usize],
    pub source_port: [::core::ffi::c_char; 64usize],
    pub target_block: [::core::ffi::c_char; 64usize],
    pub target_port: [::core::ffi::c_char; 64usize],
}
#[doc = " A flow definition."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiFlowDefinition {
    pub name: [::core::ffi::c_char; 64usize],
    pub block_count: u32,
}
#[doc = " A flow execution."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiFlowExecution {
    pub name: [::core::ffi::c_char; 64usize],
    pub pid: u64,
}
#[doc = " A model manifest."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiModelManifest {
    pub name: [::core::ffi::c_char; 64usize],
    pub size: u64,
}
#[doc = " A module registration."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AsiModuleRegistration {
    pub name: [::core::ffi::c_char; 64usize],
}
extern "C" {
    #[must_use]
    #[doc = " Creates a new SDK instance."]
    pub fn asiCreateInstance(
        reserved: *const ::core::ffi::c_void,
        instance: *mut AsiInstance,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Destroys an SDK instance."]
    pub fn asiDestroyInstance(instance: AsiInstance) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates block parameters."]
    pub fn asiEnumerateBlockParameters(
        instance: AsiInstance,
        block: *const AsiBlockDefinition,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiBlockParameter,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates block ports."]
    pub fn asiEnumerateBlockPorts(
        instance: AsiInstance,
        block: *const AsiBlockDefinition,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiBlockPort,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates block definitions."]
    pub fn asiEnumerateBlocks(
        instance: AsiInstance,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiBlockDefinition,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates flow blocks."]
    pub fn asiEnumerateFlowBlocks(
        instance: AsiInstance,
        flow: *const AsiFlowDefinition,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiBlockUsage,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates flow connections."]
    pub fn asiEnumerateFlowConnections(
        instance: AsiInstance,
        flow: *const AsiFlowDefinition,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiFlowConnection,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates flow executions."]
    pub fn asiEnumerateFlowExecutions(
        instance: AsiInstance,
        flow: *const AsiFlowDefinition,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiFlowExecution,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates flow definitions."]
    pub fn asiEnumerateFlows(
        instance: AsiInstance,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiFlowDefinition,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates model manifests."]
    pub fn asiEnumerateModels(
        instance: AsiInstance,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiModelManifest,
    ) -> AsiResult;
}
extern "C" {
    #[must_use]
    #[doc = " Enumerates module registrations."]
    pub fn asiEnumerateModules(
        instance: AsiInstance,
        buffer_capacity: u32,
        actual_count: *mut u32,
        buffer: *mut AsiModuleRegistration,
    ) -> AsiResult;
}
extern "C" {
    #[doc = " Returns the SDK build's licensee string, if any."]
    pub fn asiGetLicenseeString() -> *const ::core::ffi::c_char;
}
extern "C" {
    #[doc = " Returns the SDK's current version as a packed integer."]
    pub fn asiGetVersion() -> AsiVersion;
}
extern "C" {
    #[doc = " Returns the SDK's current version as a string."]
    pub fn asiGetVersionString() -> *const ::core::ffi::c_char;
}
extern "C" {
    #[must_use]
    #[doc = " Initializes the SDK's global state."]
    pub fn asiInitLibrary(
        reserved: *const ::core::ffi::c_void,
        print_callback: *mut ::core::ffi::c_void,
    ) -> AsiResult;
}
